# Site settings
title: Abiodun Oladipupo Data Analysis Portfolio
description: Welcome to Abiodun Oladipupo Portfolio. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abiodun Oladipupo
user_description: Abiodun Oladipupo is a passionate tech enthusiast with a strong background in teaching, graphics design, and data analysis. Passionate about education and skilled in creating engaging learning environments. Experienced in teaching diverse subjects and adept at developing tailored lesson plans. As a tech enthusiast, I am driven by my love for technology and its transformative impact on
 various fields. I have successfully leveraged my enthusiasm to excel in roles such as Research Assistant, Virtual Assistant,
 Headteacher, Secondary School Teacher, Graphics Designer, and Customer Service Representative. With a strong foundation in
 technology and a broad range of skills, I bring a unique perspective and a problem-solving mindset to any project or
 organization I engage with.
user_title: Data Analyst
email: oladipupoabiodunbamidele@gmail.com
twitter_username: olabamidele2015
github_username:  Superbiodun09
gplus_username:  oladipupoabiodunbamidele@gmail.com

# Google-analytics
google-analytics:
  id: "oladipupoabiodunbamidele@gmail.com"

exclude: ['package.json', 'src' , 'node_modules']
