# Site settings
title: Abiodun Oladipupo Data Analysis Portfolio
description: Welcome to Abiodun Oladipupo Portfolio. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abiodun Oladipupo
user_description: Hi there! I'm Abiodun, a dedicated data analyst passionate about transforming raw data into actionable insights. With a background in statistical analysis, data visualization, and predictive modelling, I engage in uncovering trends and patterns that drive informed decision-making. 
Throughout my period of learning, I've had the privilege of working on diverse projects, from optimizing business processes to crafting compelling data narratives. I believe in the power of collaboration and continuous learning, always seeking opportunities to grow and adapt in the ever-evolving field of data analytics.
Let's work together and explore how my expertise in data analysis can contribute to your organization's success! 
user_title: Data Analyst
email: oladipupoabiodunbamidele@gmail.com
twitter_username: olabamidele2015
github_username:  Superbiodun09
gplus_username:  oladipupoabiodunbamidele@gmail.com

# Google-analytics
google-analytics:
  id: "oladipupoabiodunbamidele@gmail.com"

exclude: ['package.json', 'src' , 'node_modules']
